/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chest/model.glb --transform -o public/models/chest/Chest.jsx 
Files: public/models/chest/model.glb [3.98MB] > C:\websites\garudahacks\Frontend\public\models\chest\model-transformed.glb [441.82KB] (89%)
Author: Toni García Vilche (https://sketchfab.com/zul_gv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-chest-ae71996536344b5d80e4b50ca308c438
Title: Stylized Chest
*/

import React, { useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useModalStore } from '../../../store/modalStore'
import { RigidBody } from "@react-three/rapier";

export function Chest(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/chest/model-transformed.glb')
  const { actions } = useAnimations(animations, group)

  // const [isOpen, setIsOpen] = useState(false);
  // const openModal = useModalStore((state) => state.openModal);

  useEffect(() => {
    if (actions.Open_Chest) {
      actions.Open_Chest.reset().fadeIn(0.5).play()
    }
  }, [actions])

  return (
    <RigidBody type="fixed" colliders="trimesh" {...props}>
      <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <group name="RootNode" scale={0.007}>
            <group name="Chest_Top" position={[-118.736, 165.022, 0]} rotation={[-Math.PI / 2, -0.009, 0]} scale={100}>
              <mesh name="Chest_Top_Final_Chest_0" geometry={nodes.Chest_Top_Final_Chest_0.geometry} material={materials.Final_Chest} />
            </group>
          </group>
          <mesh name="Coins_Final_Chest_0" geometry={nodes.Coins_Final_Chest_0.geometry} material={materials.Final_Chest} position={[0.015, 1.14, -0.026]} rotation={[-1.348, -0.146, -1.324]} scale={0.126} />
        </group>
      </group>
    </RigidBody>
  )
}

useGLTF.preload('/models/chest/model-transformed.glb')
