/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tugu/tugu.glb --transform -o public/models/tugu/Tugu.jsx 
Files: public/models/tugu/tugu.glb [2.09MB] > C:\websites\garudahacks\Frontend\public\models\tugu\tugu-transformed.glb [106.22KB] (95%)
Author: Djonk (https://sketchfab.com/Djonk)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/tugu-jogja-c3ab136a6fb643c09c1a4fc30402dafd
Title: Tugu Jogja
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useModalStore } from '../../../store/modalStore';
import { RigidBody } from "@react-three/rapier";


export function Tugu(props) {
  const { nodes, materials } = useGLTF('/models/tugu/tugu-transformed.glb')
  const openModal = useModalStore((state) => state.openModal);

  const handleClick = () => {
    openModal();
  };
  return (
    <RigidBody type="fixed" colliders="trimesh" {...props}>
      <group dispose={null} onClick={handleClick}>
        <mesh
          geometry={nodes.Cube_Material_0.geometry}
          material={materials.Material}
          rotation={[-Math.PI / 2, 0, 0]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Cube_Material001_0.geometry}
          material={materials["Material.001"]}
          rotation={[-Math.PI / 2, 0, 0]}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.Plane__0.geometry}
          material={materials.Plane__0}
          position={[0, 1.533, 0.291]}
          scale={0.048}
          castShadow
          receiveShadow
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload('/models/tugu/tugu-transformed.glb')
